language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  matrix:
   - $DJANGO_VERSION="<1.9"
   - $DJANGO_VERSION="<1.10"
   - $DJANGO_VERSION="<1.11"
   - $DJANGO_VERSION="<2"

install:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install psycopg2cffi; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py develop

before_script:
  - psql -c 'create database dts_test_project;' -U postgres


script: ./run_tests.sh
