version: '3.7'

services:
  db:
    image: postgres
    container_name: django_tenants_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_tenants
      - POSTGRES_PASSWORD=django_tenants
      - POSTGRES_DB=django_tenants
  web:
    build: .
    command: gunicorn drawshapes.wsgi:application --bind 0.0.0.0:8000
    container_name: django_tenants_web
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_USER=django_tenants
      - DATABASE_PASSWORD=django_tenants
      - DATABASE_DB=django_tenants
      - DATABASE_HOST=db
